### ISSUE TITLE
Python API and possible updates needed

### ISSUE THREAD

**Issue by nixjdm** [jwodder/qypi#1]
Hi! I've been looking for an hour or so for a pre-built lib for getting Python package info and repository info from GitHub, Bitbucket, and others like stars / forks / contributors / latest commit / etc. I figured this probably exists and I didn't need to write it, and this project looks like the best fit so far for getting info about Python packages from PyPI. This repo looks pretty current, which is encouraging. I tried `qypi info black` though, which did not work. Maybe something broke in the last few months with the rollout of pypi.org?

I see the focus is on the CLI, but I'm more interested in a Python API. Perhaps it's an easy transition. I'm going through your code and trying things out in IPython. Any tips? If it's all easy, an addition to the docs would be appreciated. I guess I just noticed this project and wanted to provide a little feedback since it doesn't seem too widely known.  :)

So far, I've got 

```python
from qypi.api import QyPI
a = QyPI('https://pypi.org/pypi')
pkg = a.get_package('flask')
print(pkg['info']['description'])
```
which seems to work alright. Pretty straight forward.

Thanks!

**Comment by jwodder** [comment]
`qypi`'s internals are not part of the public API (especially for the purposes of [semantic versioning](https://semver.org), i.e., the internals can change at any time), and I'd rather keep it that way so that things stay simple.

> I tried `qypi info black` though, which did not work.

As can be seen with `qypi releases black`, all `black` releases on PyPI are prerelease versions.  `qypi` works the way pip works (or, at least, the way I thought it worked), by ignoring pre-release versions unless `--pre` is supplied, so you need to run `qypi info --pre black`.
